modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory T
license="MIT"
[[mods]] #mandatory
modId="visible_toggle_sprint" #mandatory
version="${file.jarVersion}" #mandatory
displayName="VisibleToggleSprint" #mandatory
logoFile="assets/visible_toggle_sprint/icon.png" #optional
logoBlur=false
credits="" #optional
authors="TheEnderCore" #optional
# (#mandatory)
description='''
A simple mod to make toggle sprint & sneak easier!
'''
[[dependencies.visible_toggle_sprint]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.visible_toggle_sprint]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.visible_toggle_sprint]]
    modId = "yet_another_config_lib_v3"
    mandatory = true
    versionRange = "[3,)"
    ordering = "NONE"
    side = "CLIENT"

